export const WheelActionTypes = {
  SET_BONUS_LIST: "SET_BONUS_LIST",
  SET_BONUS: "SET_BONUS",
  OPEN_WHEEL_MODAL: "OPEN_WHEEL_MODAL",
  IS_WANT_MORE_CHANCE_MODAL_OPEN: "IS_WANT_MORE_CHANCE_MODAL_OPEN,",
};
