export const LeaderboardActionTypes = {
  SET_LEADERBOARD_HEADER_STATUS: "SET_LEADERBOARD_HEADER_STATUS",
  USER_LIST_WEEKLY: "USER_LIST_WEEKLY",
  USER_LIST_MONTHLY: "USER_LIST_MONTHLY",
  USER_LIST_SEASONAL: "USER_LIST_SEASONAL",
};
