export const UserActionTypes = {
  SET_ACCESS_TOKEN: "SET_ACCESS_TOKEN",
  SET_REFRESH_TOKEN: "SET_REFRESH_TOKEN",
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SET_OPEN_VALIDATION_DIALOG: "SET_OPEN_VALIDATION_DIALOG",
  SET_ALL_USER_ADDRESSES: "SET_ALL_USER_ADDRESSES",
};
