export const GamesActionTypes = {
  GET_ALL_GAMES: "GET_ALL_GAMES",
  GET_FILTERED_CATEGORY: "GET_FILTERED_CATEGORY",
  GET_SEARCHED_ITEM: "GET_SEARCHED_ITEM",
  GET_GAME_DETAILS: "GET_GAME_DETAILS",
  GET_USER_APPLICATION_INFO: "GET_USER_APPLICATION_INFO",
  IS_APPLICATION_INSTALLED: "IS_APPLICATION_INSTALLED",
};
